-- =====================================================================
-- TURNO D · esquema de base de datos (Supabase / PostgreSQL)
-- Pegar entero en Supabase → SQL Editor → Run. Se puede ejecutar una sola vez
-- sobre un proyecto vacío.
-- =====================================================================

-- ---------- Tablas ----------
create table public.empleados (
  id         integer generated by default as identity primary key,
  nombre     text    not null unique,
  email      text    unique,                       -- el de su cuenta de acceso (se rellena después)
  rol        text    not null default 'agente' check (rol in ('agente','responsable')),
  pareja_id  integer references public.empleados(id),
  orden      integer not null,
  activo     boolean not null default true,
  hace_pico  boolean not null default true          -- false = nunca se le pone PICO
);

create table public.codigos (
  codigo               text primary key,
  descripcion          text    not null,
  tipo                 text    not null check (tipo in ('Ausencia Justificada','Tipo trabajo','Especial')),
  cuenta_como_trabajo  boolean not null default false,
  solo_responsables    boolean not null default false,
  orden                integer not null
);

create table public.dias (                           -- ciclo de turnos de cada día: M, T, N, S (saliente) o L (libre)
  fecha  date primary key,
  turno  text not null check (turno in ('M','T','N','S','L'))
);

create table public.asignaciones (                   -- una fila por persona y día con código; sin fila = día normal
  empleado_id     integer not null references public.empleados(id) on delete cascade,
  fecha           date    not null,
  codigo          text    not null references public.codigos(codigo),
  actualizado_por integer references public.empleados(id),
  actualizado_en  timestamptz not null default now(),
  primary key (empleado_id, fecha)
);

create table public.config (
  clave  text primary key,
  valor  text not null
);

create table public.cambios (                        -- historial; de aquí saldrán los avisos al equipo
  id            bigint generated always as identity primary key,
  creado_en     timestamptz not null default now(),
  empleado_id   integer not null,
  fecha         date    not null,
  codigo_antes  text,
  codigo_despues text,
  hecho_por     integer
);
create index on public.cambios (creado_en desc);

-- ---------- Funciones auxiliares ----------
-- Quién es la persona que ha iniciado sesión: se busca su email en la tabla de empleados.
create or replace function public.mi_empleado_id() returns integer
language sql stable security definer set search_path = public as $$
  select id from public.empleados
  where activo and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  limit 1
$$;

create or replace function public.soy_responsable() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.empleados
    where activo and rol = 'responsable'
      and lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  )
$$;

create or replace function public.codigo_solo_responsables(c text) returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((select solo_responsables from public.codigos where codigo = c), false)
$$;

-- ---------- Triggers ----------
create or replace function public.asignaciones_antes() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.codigo = 'PICO' and exists (select 1 from public.empleados where id = new.empleado_id and not hace_pico) then
    raise exception 'Esta persona no hace PICO';
  end if;
  new.actualizado_por := public.mi_empleado_id();
  new.actualizado_en  := now();
  return new;
end $$;

create trigger asignaciones_antes before insert or update on public.asignaciones
  for each row execute function public.asignaciones_antes();

create or replace function public.asignaciones_despues() returns trigger
language plpgsql security definer set search_path = public as $$
declare quien integer := public.mi_empleado_id();
begin
  if quien is null then return null; end if;        -- importaciones y cambios hechos desde el panel no se registran
  if tg_op = 'INSERT' then
    insert into public.cambios(empleado_id, fecha, codigo_antes, codigo_despues, hecho_por)
    values (new.empleado_id, new.fecha, null, new.codigo, quien);
  elsif tg_op = 'UPDATE' then
    if old.codigo is distinct from new.codigo then
      insert into public.cambios(empleado_id, fecha, codigo_antes, codigo_despues, hecho_por)
      values (new.empleado_id, new.fecha, old.codigo, new.codigo, quien);
    end if;
  else
    insert into public.cambios(empleado_id, fecha, codigo_antes, codigo_despues, hecho_por)
    values (old.empleado_id, old.fecha, old.codigo, null, quien);
  end if;
  return null;
end $$;

create trigger asignaciones_despues after insert or update or delete on public.asignaciones
  for each row execute function public.asignaciones_despues();

-- ---------- Seguridad: nadie ve ni toca nada sin estar en la tabla de empleados ----------
revoke all on all tables    in schema public from anon;
revoke all on all functions in schema public from anon;

alter table public.empleados    enable row level security;
alter table public.codigos      enable row level security;
alter table public.dias         enable row level security;
alter table public.asignaciones enable row level security;
alter table public.config       enable row level security;
alter table public.cambios      enable row level security;

-- Lectura: cualquier persona dada de alta (con su email en empleados)
create policy leer_empleados    on public.empleados    for select to authenticated using (public.mi_empleado_id() is not null);
create policy leer_codigos      on public.codigos      for select to authenticated using (public.mi_empleado_id() is not null);
create policy leer_dias         on public.dias         for select to authenticated using (public.mi_empleado_id() is not null);
create policy leer_asignaciones on public.asignaciones for select to authenticated using (public.mi_empleado_id() is not null);
create policy leer_config       on public.config       for select to authenticated using (public.mi_empleado_id() is not null);
create policy leer_cambios      on public.cambios      for select to authenticated using (public.mi_empleado_id() is not null);

-- Tablas de gestión: solo responsables
create policy gestionar_empleados on public.empleados for all to authenticated using (public.soy_responsable()) with check (public.soy_responsable());
create policy gestionar_codigos   on public.codigos   for all to authenticated using (public.soy_responsable()) with check (public.soy_responsable());
create policy gestionar_dias      on public.dias      for all to authenticated using (public.soy_responsable()) with check (public.soy_responsable());
create policy gestionar_config    on public.config    for all to authenticated using (public.soy_responsable()) with check (public.soy_responsable());

-- Calendario: responsables editan a todos; el resto solo sus días y nunca códigos reservados (PICO, DESP…)
create policy crear_asignaciones on public.asignaciones for insert to authenticated
  with check (public.soy_responsable()
              or (empleado_id = public.mi_empleado_id() and not public.codigo_solo_responsables(codigo)));

create policy cambiar_asignaciones on public.asignaciones for update to authenticated
  using      (public.soy_responsable()
              or (empleado_id = public.mi_empleado_id() and not public.codigo_solo_responsables(codigo)))
  with check (public.soy_responsable()
              or (empleado_id = public.mi_empleado_id() and not public.codigo_solo_responsables(codigo)));

create policy borrar_asignaciones on public.asignaciones for delete to authenticated
  using (public.soy_responsable()
         or (empleado_id = public.mi_empleado_id() and not public.codigo_solo_responsables(codigo)));

-- Cambios en vivo: si alguien edita, los demás lo ven sin recargar
do $$ begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.asignaciones;
    alter publication supabase_realtime add table public.cambios;
  end if;
end $$;
